// DOM & Utility Helper Functions
const Helpers = {
  getEl: (id) => document.getElementById(id),
  getQuery: (sel) => document.querySelector(sel),
  getAll: (sel) => document.querySelectorAll(sel),
  setText: (el, txt) => { if(el) el.textContent = txt; },
  setHTML: (el, html) => { if(el) el.innerHTML = html; },
  setAttr: (el, attr, val) => { if(el) el.setAttribute(attr, val); },
  getAttr: (el, attr) => el ? el.getAttribute(attr) : null,
  addClass: (el, cls) => { if(el) el.classList.add(cls); },
  removeClass: (el, cls) => { if(el) el.classList.remove(cls); },
  toggleClass: (el, cls) => { if(el) el.classList.toggle(cls); },
  hasClass: (el, cls) => el ? el.classList.contains(cls) : false,
  show: (el) => { if(el) el.style.display = ''; },
  hide: (el) => { if(el) el.style.display = 'none'; },
  toggle: (el) => { if(el) el.style.display = el.style.display === 'none' ? '' : 'none'; },
  capitalize: (str) => str ? str.charAt(0).toUpperCase() + str.slice(1) : '',
  trim: (str) => str ? str.trim() : '',
  isEmpty: (str) => !str || str.trim() === '',
  delay: (ms) => new Promise(r => setTimeout(r, ms)),
  debounce: (fn, ms) => { let timer; return (...args) => { clearTimeout(timer); timer = setTimeout(() => fn(...args), ms); }; },
  log: (msg) => console.log(`[App] ${msg}`),
  error: (msg) => console.error(`[Error] ${msg}`),
};
